ApiSystemArchiveDoc/Controllers/ArchiveObjectController.cs
using ApiSystemArchiveDoc.Models;
using ApiSystemArchiveDoc.Models.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Swashbuckle.AspNetCore.SwaggerGen;
using SystemArchiveDocDAL;
using SystemArchiveDocDAL.Repositories;
using SystemArchiveDocDomain;
using SystemArchiveDocDomain.Interfaces.Services;
using SystemArhiveDocInfrastucture.Services;

namespace ApiSystemArchiveDoc.Controllers;

[Authorize]
[ApiExplorerSettings(IgnoreApi = true)]
[Route("{controller}/{action}")]
public class ArchiveObjectController : Controller
{
    private IArchiveObjectService _service;

    // GET
    public ArchiveObjectController(IArchiveObjectService service)
    {
        _service = service;
    }

    [Authorize]

    public async Task<IActionResult> Index()
    {
        var u = (User.Identity as ApiSystemArchiveDocUser);
        var objectTypes = (await _service.GetObjectTypes()).Select(x => new SelectListItem()
        {
            Text = x.Name,
            Value = x.Id.ToString()
        });
        var taskTypes = (await _service.GetTaskTypesAsync()).Select(x => new SelectListItem()
        {
            Text = x.Name,
            Value = x.Id.ToString()
        });
        var documentTypes = (await _service.GetDocumentTypesAsync()).Select(x => new SelectListItem()
        {
            Text = x.Name,
            Value = x.Id.ToString()
        });
        return View("Index", new ArchiveDocumentObjectIndexModel()
        {
            RefLink = HttpContext.Request.Path + HttpContext.Request.QueryString.Value,
            ArchiveObjects = (await _service.GetObjectsAsync()).Select(o =>
                new ArchiveObjectModel()
                {
                    Id = o.Id,
                    Square = o.Square.Value,
                    FullAddress = o.Address.FullAddress,
                    ObjectType = o.ObjectType.Name,
                    ObjectTaskType = o.TaskType.Name,
                    CreateDateTime = o.Created,
                    StatusStr = o.Status.Name
                }).ToList()
        });
    }

    #region Create
    [Authorize]

    [HttpGet]
    public async Task<IActionResult> Create()
    {
        var objectTypes = (await _service.GetObjectTypes()).Select(x => new SelectListItem()
        {
            Text = x.Name,
            Value = x.Id.ToString()
        });


        var taskTypes = (await _service.GetTaskTypesAsync()).Select(x => new SelectListItem()
        {
            Text = x.Name,
            Value = x.Id.ToString()
        });
        var documentTypes = (await _service.GetDocumentTypesAsync()).Select(x => new SelectListItem()
        {
            Text = x.Name,
            Value = x.Id.ToString()
        });
        ViewData["Action"] = "Create";

        return View("CreateOrEdit", new ArchiveObjectCreateOrEditModel()
        {
            ObjectTypes = objectTypes.ToList(),
            TaskTypes = taskTypes.ToList(),
            DocumentTypes = documentTypes.ToList(),
            StatusStr = "Без статуса",
            StatusCodeStr = "01",
            Region = "Донецкая Народная Респ",
            RefLink = HttpContext.Request.Path + HttpContext.Request.QueryString.Value,
        });
    }
    
    [Authorize]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(ArchiveObjectCreateOrEditModel model)
    {
        var objectTypes = (await _service.GetObjectTypes()).Select(x => new SelectListItem()
        {
            Text = x.Name,
            Value = x.Id.ToString()
        });
        var taskTypes = (await _service.GetTaskTypesAsync()).Select(x => new SelectListItem()
        {
            Text = x.Name,
            Value = x.Id.ToString()
        });
        var documentTypes = (await _service.GetDocumentTypesAsync()).Select(x => new SelectListItem()
        {
            Text = x.Name,
            Value = x.Id.ToString()
        });

        if (ModelState.IsValid)
        {
            var archiveObject = await _service.CreateOrEditArchiveObjectAsync(
                new SystemArchiveObject()
                {
                    Created = DateTime.Now,
                    Square = model.Square,
                    Status = (await _service.GetStatusesAsync()).First(x => x.Code == "20"),
                    Address = new SystemArchiveAddress()
                    {
                        Region = model.Region,
                        Area = model.Area,
                        City = model.City,
                        CityArea = model.CityArea,
                        CityDistrict = model.CityDistrict,
                        Settlement = model.Settlement,
                        Street = model.Street,
                        House = model.House,
                        Block = model.Block,
                        Floor = model.Floor,
                        Flat = model.Flat,
                        Stead = model.Stead,
                        Okato = model.Okato,
                        Oktmo = model.Oktmo,
                        GeoLat = model.GeoLat,
                        GeoLon = model.GeoLon,
                        FullAddress = @$"{model.KadKvartal} {(await _service.GetObjectTypes())
                            .FirstOrDefault(x => x.Id.ToString() == model.ObjectType)?.Name} "
                                      + $@"{model.Region},"
                                      + (string.IsNullOrEmpty(model.Area) ? string.Empty : model.Area + ",")
                                      + (string.IsNullOrEmpty(model.City) ? string.Empty : model.City + ",")
                                      + (string.IsNullOrEmpty(model.CityArea) ? string.Empty : model.CityArea + ",")
                                      + (string.IsNullOrEmpty(model.CityDistrict)
                                          ? string.Empty
                                          : model.CityDistrict + ",")
                                      + (string.IsNullOrEmpty(model.Settlement) ? string.Empty : model.Settlement + ",")
                                      + (string.IsNullOrEmpty(model.House) ? string.Empty : "д. " + model.House + ",")
                                      + (string.IsNullOrEmpty(model.Block) ? string.Empty : "" + model.Block + ",")
                                      + (string.IsNullOrEmpty(model.Floor) ? string.Empty : "этаж " + model.Floor + ",")
                                      + (string.IsNullOrEmpty(model.Flat) ? string.Empty : "кв. " + model.Flat + ",")
                                      + (string.IsNullOrEmpty(model.Flat)
                                          ? string.Empty
                                          : "з.у. номер. " + model.Flat + ",")
                    },

                    ObjectType =
                        (await _service.GetObjectTypes()).FirstOrDefault(x => x.Id.ToString() == model.ObjectType),
                    TaskType = (await _service.GetTaskTypesAsync()).FirstOrDefault(x =>
                        x.Id.ToString() == model.ObjectTaskType),
                    KadKvartal = model.KadKvartal,
                });
            if (Guid.Empty != archiveObject.Id || archiveObject.Id != null)
               return RedirectToAction("Edit", new {Id = archiveObject.Id.ToString()});

        }
       

        return View("CreateOrEdit", new ArchiveObjectCreateOrEditModel()
        {
            ObjectTypes = objectTypes.ToList(),
            TaskTypes = taskTypes.ToList(),
            DocumentTypes = documentTypes.ToList(),

            RefLink = HttpContext.Request.Path + HttpContext.Request.QueryString.Value,
        });
    }

    #endregion

    #region Edit
    [Authorize]
    public async Task<IActionResult> Edit(string Id)
    {
        var u = (User.Identity as ApiSystemArchiveDocUser);

        var archiveObject = await _service.GetObjectById(Guid.Parse(Id));


        var objectTypes = (await _service.GetObjectTypes()).Select(x => new SelectListItem()
        {
            Text = x.Name,
            Value = x.Id.ToString(),
            Selected = x.Id == archiveObject.ObjectType.Id
        });
        var taskTypes = (await _service.GetTaskTypesAsync()).Select(x => new SelectListItem()
        {
            Text = x.Name,
            Value = x.Id.ToString(),
            Selected = x.Id == archiveObject.TaskType.Id
        });
        var documentTypes = (await _service.GetDocumentTypesAsync()).Select(x => new SelectListItem()
        {
            Text = x.Name,
            Value = x.Id.ToString()
        });
        ViewData["Action"] = "Edit";
        return View("CreateOrEdit", new ArchiveObjectCreateOrEditModel()
        {
            StatusStr = archiveObject.Status.Name,
            StatusCodeStr = archiveObject.Status.Code,
            ObjectTypes = objectTypes.ToList(),
            TaskTypes = taskTypes.ToList(),
            DocumentTypes = documentTypes.ToList(),
            KadKvartal = archiveObject.KadKvartal,
            ObjectType = archiveObject.ObjectType.Id.ToString(),
            ObjectTaskType = archiveObject.TaskType.Id.ToString(),
            Square = archiveObject.Square.Value,
            RefLink = HttpContext.Request.Path + HttpContext.Request.QueryString.Value,
            Region = archiveObject.Address.Region,
            Area = archiveObject.Address.Area,
            City = archiveObject.Address.City,
            CityArea = archiveObject.Address.CityArea,
            CityDistrict = archiveObject.Address.CityDistrict,
            Settlement = archiveObject.Address.Settlement,
            Street = archiveObject.Address.Street,
            House = archiveObject.Address.House,
            Block = archiveObject.Address.Block,
            Floor = archiveObject.Address.Floor,
            Flat = archiveObject.Address.Flat,
            Stead = archiveObject.Address.Stead,
            Okato = archiveObject.Address.Okato,

ApiSystemArchiveDoc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Оцифровка архива</title>
    <script src="~/js/bundles.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap-multiselect.min.js"></script>
    <script src="~/js/jquery.inputmask.min.js"></script>
    <script src="~/js/inputmask.min.js"></script>


    <link href="~/lib/fontawesome/fontawesome-free-6.0.0-beta3-web/css/all.css" rel="stylesheet">
    <link href="~/css/site.min.css" rel="stylesheet">
    <link href="~/lib/bootstrap/dist/css/bootstrap-multiselect.min.css" rel="stylesheet">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" type="image/ico" href="@Url.Content("~/favicon.ico")">
    <link href="~/img/favicon.ico" rel="shortcut icon" type="image/x-icon"/>

</head>
<body>

<div class="container">
    <div class="preloader" style="display: none">
        <div class="loader"></div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">


        <a class="navbar-brand" href="#">
            <img src="~/img/logo.png" width="80px" class="d-inline-block fa-align-center" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler"
                aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id='navbarToggler'>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    @Html.ActionLink("Оцифровка архива онлайн", "Index",
                        "Home", new { }, new { @class = "nav-link" })
                </li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        @Html.ActionLink("Объекты", "Index",
                            "ArchiveObject", new { }, new { @class = "nav-link" })
                    </li>
                    @if (User.IsInRole("IsAdministrator"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                               aria-expanded="false">
                                Администрирование
                            </a>
                            <div class="dropdown-menu">
                                <a class="nav-link" href="~/Identity/Account/Users">Пользователи</a>
                                @Html.ActionLink(" Отчеты", "Index", "Report",
                                    new
                                    {
                                        depatrmentsId = new List<long>() { 0 },
                                        servicesCode = new List<String>() { "0" }, date = DateTime.Now, stopdate = DateTime.Now.AddDays(1)
                                    }, new { @class = "nav-link" })
                                <div class="dropdown-divider"></div>
                                <a class="nav-link" href="~/Identity/Account/Users">Внести сведения из ССС</a>
                            </div>
                        </li>

                     
                    }
                }
            </ul>

            @Html.Partial("_LoginPartial")
        </div>
    </nav>


</div>

<div class="container body-content">
    @RenderBody()
    <hr/>

    <footer>
        <p>&copy; @DateTime.Now.Year - Оцифровка архива</p>
    </footer>
</div>

</body>
</html>